version: '3'
services:
  ml-backend:
    image: ml_pipeline:latest
    command: python -m uvicorn app:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - ./model.pkl:/app/model.pkl
      - ./churn-bigml-80.csv:/app/churn-bigml-80.csv
      - ./churn-bigml-20.csv:/app/churn-bigml-20.csv
      - ./test_results_fallback.json:/app/test_results.json
    environment:
      - PORT=8000
    networks:
      - ml-network

  frontend:
    image: ml_pipeline_frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - ml-backend
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    networks:
      - ml-network
    # Remove the command here since we're adding it to Dockerfile

networks:
  ml-network:
    driver: bridge
